name: Wanderlust webapp ci/cd

on:
    push:
        branches:
            - main
jobs:
    Validate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

    Docker-setup:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2  

            - name: Location
              run: ls frontend
              
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        
            - name: Build and Push Docker Image
              uses: docker/build-push-action@v4
              with:
                context: ./frontend
                file: ./frontend/Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapp:${{ github.run_id }}
                
            - name: Dokcer Run
              run: |
                   docker pull ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
                   docker run -d -p 8080:80 --name wanderlust-webapp ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest


    Stop-container:
        runs-on: ubuntu-latest
        needs: Docker-setup
        if: always(}
        steps:
          - name: Docker container stop
            run: |
              docker stop wanderlust-webapp || echo "Container not running"
              docker rm wanderlust-webapp || echo "Container not found"
          
        
